### ISSUE TITLE
Friend Code!

### ISSUE THREAD

**Issue by ancarda** [kaktusas2598/project_euler#1]
Hey @kaktusas2598, I didn't know you we're working on Project Euler as well! Could you send me your friend code? Mine is `1282962_t9oKlegywXqspZyZgRmD7xW9B62vFNZD`.

Would be good to compare progress.

**Comment by kaktusas2598** [comment]
Hey @ancarda ! Last commit in this repo - 3 years ago! So yeah, I was doing this long time ago. Added you to my friends, here is my code `144506_CbEVGoVS3rG8WWQfn8lmslsyRoIxBPif` ! It's a bit unfair as I am not doing this anymore haha . Have you tried code wars?

**Comment by ancarda** [comment]
I've never heard of Code Wars, I [just signed up now](https://www.codewars.com/users/ancarda). Already stuck on an puzzle.
